/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.administrator;

import gui.mainFrame.Administrator_P;
import gui.mainFrame.SignIn_Admin;
import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author shalaka
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        setOpaque(false); // Make the panel transparent so we can paint a rounded background
        setBackground(new Color(100, 150, 200)); // Choose your background color
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Set the background color for the rounded panel
        g2.setColor(getBackground());

        // Define the rounded rectangle shape
        int arcWidth = 50;  // Adjust these values for roundness
        int arcHeight = 50;
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), arcWidth, arcHeight);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_customer = new javax.swing.JButton();
        btn_employee = new javax.swing.JButton();
        btn_event = new javax.swing.JButton();
        btn_invoice = new javax.swing.JButton();
        btn_report = new javax.swing.JButton();
        btn_booking = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_jobrole = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btn_stock = new javax.swing.JButton();
        btn_brand = new javax.swing.JButton();
        btn_grn = new javax.swing.JButton();
        btn_category = new javax.swing.JButton();

        btn_customer.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btn_customer.setText("Customer");
        btn_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_customerActionPerformed(evt);
            }
        });

        btn_employee.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btn_employee.setText("Employee");
        btn_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_employeeActionPerformed(evt);
            }
        });

        btn_event.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btn_event.setText("Event");
        btn_event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eventActionPerformed(evt);
            }
        });

        btn_invoice.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btn_invoice.setText("Invoice");

        btn_report.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btn_report.setText("Report");

        btn_booking.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btn_booking.setText("Booking");
        btn_booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookingActionPerformed(evt);
            }
        });

        btn_logout.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btn_logout.setText("Log Out");

        btn_jobrole.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btn_jobrole.setText("Job Role");
        btn_jobrole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jobroleActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/menu icon 25-25.png"))); // NOI18N

        btn_stock.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btn_stock.setText("Stock");
        btn_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stockActionPerformed(evt);
            }
        });

        btn_brand.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btn_brand.setText("Brand");

        btn_grn.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btn_grn.setText("GRN");

        btn_category.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btn_category.setText("Category");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_employee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_event, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_booking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_report, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_invoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_jobrole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_brand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_grn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_category, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(btn_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_jobrole, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_event, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_booking, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_brand, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_category, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_report, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_grn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stockActionPerformed
        //        jPanel5.removeAll();
        //        jPanel5.add(new StockManagement());
        //        jPanel5.revalidate();
        //        jPanel5.repaint();
    }//GEN-LAST:event_btn_stockActionPerformed

    private void btn_jobroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jobroleActionPerformed
//                jPanel5.removeAll();
//                jPanel5.add(new JobRoleManagement());
//                jPanel5.revalidate();
//                jPanel5.repaint();
    }//GEN-LAST:event_btn_jobroleActionPerformed

    private void btn_bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_bookingActionPerformed

    private void btn_eventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eventActionPerformed
        //        jPanel5.removeAll();
        //        jPanel5.add(new EventManagement());
        //        jPanel5.revalidate();
        //        jPanel5.repaint();
    }//GEN-LAST:event_btn_eventActionPerformed

    private void btn_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_employeeActionPerformed
        //        jPanel5.removeAll();
        //        jPanel5.add(new EmployeeManagement());
        //        jPanel5.revalidate();
        //        jPanel5.repaint();

        Administrator admin = (Administrator) SwingUtilities.getWindowAncestor(this);
        JPanel panel5 = admin.getJPanel5();
        panel5.removeAll();
        panel5.add(new EmployeeManagement());
        panel5.revalidate();
        panel5.repaint();
    }//GEN-LAST:event_btn_employeeActionPerformed

    private void btn_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_customerActionPerformed
//        Container parent = MainPanel.this.getParent();
//
//        jPanel5.removeAll();
//        jPanel5.add(new CustomerManagement());
//        jPanel5.revalidate();
//        jPanel5.repaint();

        Administrator admin = (Administrator) SwingUtilities.getWindowAncestor(this);
        JPanel panel5 = admin.getJPanel5();
        panel5.removeAll();
        panel5.add(new CustomerManagement());
        panel5.revalidate();
        panel5.repaint();
    }//GEN-LAST:event_btn_customerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_booking;
    private javax.swing.JButton btn_brand;
    private javax.swing.JButton btn_category;
    private javax.swing.JButton btn_customer;
    private javax.swing.JButton btn_employee;
    private javax.swing.JButton btn_event;
    private javax.swing.JButton btn_grn;
    private javax.swing.JButton btn_invoice;
    private javax.swing.JButton btn_jobrole;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_report;
    private javax.swing.JButton btn_stock;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
